server:
  port: 8750
  error:
    include-message: ALWAYS

spring:
  application:
    name: blog
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  profiles:
    - active: ${PROFILE}