name: CI-CD

on:
  push:
    branches: [ 'main' ]

env:
  GKE_CLUSTER: main-1
  GKE_ZONE: europe-west1-b
  NAME: blog
  
jobs:
  build:
    if: github.ref == 'refs/heads/main'
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: JDK 17 Set up
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Grant execute permissions for gradlew
      run: |-
        chmod +x gradlew
        
    - name: Cache gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Gradle build
      run: |-
        ./gradlew build
  
  publish:
    name: Publish to Docker
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Publish image
      run: |-
        ./gradlew dockerTagsPush
        
  rollout:
    name: Rollout restart to kubernetes
    runs-on: ubuntu-latest
    needs: [publish]
    
    steps:
    - uses: actions/checkout@v2

    - uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
        
    - name: Rollout restart of deployment
      run: |-
        kubectl rollout restart deployment/$NAME
        
